start_stickers = [
    "CAACAgIAAxkBAAMoZUPOfQABtk7WXnD39PBUEBeWI-z1AAI0AQACUomRIxPN12_1HAdYMwQ",
    "CAACAgIAAxkBAAMqZUPOiyQ21OFgMPQ_uFp0t7QMmgQAAksAA1KJkSPIbWjNP-ja6zME",
    "CAACAgIAAxkBAAMsZUPOoFiJJBlUxVeg2v80lY56TXQAAgEBAAJWnb0KIr6fDrjC5jQzBA",
    "CAACAgIAAxkBAAMuZUPOqlFug1QfaAGgAWWHTRT3nasAAiAAA1m7_CWFipaaCE3JfTME",
    "CAACAgIAAxkBAAMwZUPO8zckmfWa_zR55o5yJe8ERFgAAlQAA0G1Vgxqt_jHCI0B-jME",
    "CAACAgIAAxkBAAMyZUPPFMYxbxXDJAuzmrqemHxbRxAAAkIQAAIzxSlJkA7UEacqSoIzBA",
    "CAACAgIAAxkBAAM0ZUPPIxMcnP_g_qgW_isRI0zUg-kAAi4AAyRxYhqI6DZDakBDFDME",
    "CAACAgIAAxkBAAM2ZUPPLcoJ2KtSmnWjiM0szq8hmHsAAv8CAAJtsEIDBKA5qzQCNjczBA",
    "CAACAgIAAxkBAAM6ZUPPZWhXeG2XoLe8t7VqpFal_fsAAqkRAAIFy7lIEMswV7USGOwzBA"
]

finish_job_stickers = "CAACAgIAAxkBAAODZUPTkDBA3VsYR-MI8WctxOJuYq8AAooqAALpVQUYHKmVlckOWPwzBA"

not_pass_domain_stickers = [
    "CAACAgIAAxkBAAOHZUPT4-NacUdupdyYYtuWTBWefnAAApIqAALpVQUYhc5x7Rdfgf4zBA",
    "CAACAgIAAxkBAAOFZUPT4UKZJLLPZaZKgLdckk3pNkwAAogqAALpVQUYTb-lzC9JTjczBA",
    "CAACAgIAAxkBAAOBZUPTg3TAXtBHURLzB0yliyDWY98AAoAqAALpVQUYw_4ulIdKyd8zBA",
    "CAACAgIAAxkBAAOLZUPUx83hAhg1tC0u1bKrFZfSmVkAAnkqAALpVQUYPQmEy6Ke-pczBA"
]

pass_domain_stickers = [
    "CAACAgIAAxkBAAOJZUPUiattP-BPBgLlMSeXDlJbuusAAp0qAALpVQUYUvw-_xSspF4zBA",
    "CAACAgIAAxkBAAONZUPU1vsepkuBKTQHKEowFgy_bj8AAn8qAALpVQUY7SgzDdn9WF4zBA"
]

start_search_sticker = "CAACAgIAAxkBAAIBw2VECFpdZLW00zEO5QABh4UwoM19AwACnioAAulVBRj6xXMX7pKX5DME"
